[workspace]
resolver = "2"
members = [
    "randrw-s3-client",
    "randrw-s3-server"
]

[patch.crates-io]
hyper = { git = "https://github.com/gh-efforts/hyper.git", branch = "0.14.x" }

[profile.release]
lto = true
codegen-units = 1